// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['main']['App']['Add'](arg1);
}

export function Commit(arg1, arg2) {
  return window['go']['main']['App']['Commit'](arg1, arg2);
}

export function GetBranch(arg1) {
  return window['go']['main']['App']['GetBranch'](arg1);
}

export function GetCoreInfo() {
  return window['go']['main']['App']['GetCoreInfo']();
}

export function GetStatus(arg1) {
  return window['go']['main']['App']['GetStatus'](arg1);
}
