// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1:string):Promise<string>;

export function Commit(arg1:string,arg2:string):Promise<string>;

export function GetBranch(arg1:string):Promise<string>;

export function GetCoreInfo():Promise<string>;

export function GetStatus(arg1:string):Promise<any>;
